[package]
name = "gfx-sdl"
version = "0.1.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]

[dependencies]
gfx = "0"
gfx_text = { git = "https://github.com/alexheretic/gfx_text", branch = "forward-compat" }
gfx_window_glutin = { git = "https://github.com/alexheretic/gfx", branch = "forward-compat" }
gfx_macros = "0"
glutin = "0"

log = "0"
pretty_env_logger = "0"
time = "0"
image = "0"
cgmath = "0"
notify = "4"
