[package]
name = "gfx-sdl"
version = "0.1.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]

[dependencies]
gfx = "0.15"
gfx_macros = "0"
gfx_window_sdl = "0"
sdl2 = "0"
log = "0"
pretty_env_logger = "0"
time = "0"
image = "0"
cgmath = "0"
gfx_text = "0"
notify = "4"
